### Logearse
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{


}

###

GET http://localhost:5000/api/v1/clinic-histories/user-clinic-history
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IkNhcmxpdG9zIFRlc3R5IiwiZW1haWwiOiJlamVtcGxvMkBtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJGdFeE10OFFKTzk5dmZLSUdaZ09ZOXVmTDFiZHdvMjgxeTZQRUVXMy5xSE5DQTVsa2lFWGsuIiwic3RhdGUiOnRydWUsInJvbGUiOiJ1c2VyIiwiY3JlYXRlZEF0IjoiMjAyNC0wNy0wMlQxNzoxNzowNC4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNC0wNy0wMlQxNzoxNzowNC4wMDBaIiwiaWF0IjoxNzE5OTY4NDQ2LCJleHAiOjE3Mjc3NDQ0NDZ9.CAfzGMPHDu2iXuEez_EM_4PJxaxG0m1d9vCI1XDCfPk


###
GET http://localhost:5000/api/v1/clinic-histories/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IkNhcmxpdG9zIFRlc3R5IiwiZW1haWwiOiJlamVtcGxvMkBtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJGdFeE10OFFKTzk5dmZLSUdaZ09ZOXVmTDFiZHdvMjgxeTZQRUVXMy5xSE5DQTVsa2lFWGsuIiwic3RhdGUiOnRydWUsInJvbGUiOiJ1c2VyIiwiY3JlYXRlZEF0IjoiMjAyNC0wNy0wMlQxNzoxNzowNC4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNC0wNy0wMlQxNzoxNzowNC4wMDBaIiwiaWF0IjoxNzE5OTY4NDQ2LCJleHAiOjE3Mjc3NDQ0NDZ9.CAfzGMPHDu2iXuEez_EM_4PJxaxG0m1d9vCI1XDCfPk
###
GET http://localhost:5000/api/v1/clinic-histories/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IkNhcmxpdG9zIFRlc3R5IiwiZW1haWwiOiJlamVtcGxvMkBtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJGdFeE10OFFKTzk5dmZLSUdaZ09ZOXVmTDFiZHdvMjgxeTZQRUVXMy5xSE5DQTVsa2lFWGsuIiwic3RhdGUiOnRydWUsInJvbGUiOiJ1c2VyIiwiY3JlYXRlZEF0IjoiMjAyNC0wNy0wMlQxNzoxNzowNC4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNC0wNy0wMlQxNzoxNzowNC4wMDBaIiwiaWF0IjoxNzE5OTY4NDQ2LCJleHAiOjE3Mjc3NDQ0NDZ9.CAfzGMPHDu2iXuEez_EM_4PJxaxG0m1d9vCI1XDCfPk


###
POST http://localhost:5000/api/v1/clinic-histories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IkNhcmxpdG9zIFRlc3R5IiwiZW1haWwiOiJlamVtcGxvMkBtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJGdFeE10OFFKTzk5dmZLSUdaZ09ZOXVmTDFiZHdvMjgxeTZQRUVXMy5xSE5DQTVsa2lFWGsuIiwic3RhdGUiOnRydWUsInJvbGUiOiJ1c2VyIiwiY3JlYXRlZEF0IjoiMjAyNC0wNy0wMlQxNzoxNzowNC4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNC0wNy0wMlQxNzoxNzowNC4wMDBaIiwiaWF0IjoxNzE5OTY4NDQ2LCJleHAiOjE3Mjc3NDQ0NDZ9.CAfzGMPHDu2iXuEez_EM_4PJxaxG0m1d9vCI1XDCfPk

{
    "name": "xxxx testy",
    "fecha_nacimiento": "2000-01-01",
    "sexo": "Masculino",
    "estado_civil": "Casado/a",
    "peso": 75,
    "altura": 175,
    "grupo_sanguineo": "A RH+",
    "hipertension": 1,
    "diabetes": 0,
    "asma": 1,
    "alergias": 0,
    "insuf_cardiaca": 1,
    "tabaco": 0,
    "alcohol": 1,
    "marihuana": 0,
    "cocaina": 1,
    "otras_drogas": 0
}

